version: 2

project_name: runqy-worker

before:
  hooks:
    - go mod tidy

builds:
  - id: worker
    main: ./cmd/worker
    binary: runqy-worker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.BuildDate={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE*
      - README*
      - config.yml.example

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

dockers_v2:
  # Minimal image - multi-arch
  - id: minimal
    ids:
      - worker
    images:
      - "ghcr.io/publikey/runqy-worker"
    tags:
      - "{{ .Tag }}"
      - "{{ .Tag }}-minimal"
      - "latest"
      - "minimal"
    dockerfile: Dockerfile.minimal
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"

  # Inference image - amd64 only (CUDA)
  - id: inference
    ids:
      - worker
    images:
      - "ghcr.io/publikey/runqy-worker"
    tags:
      - "{{ .Tag }}-inference"
      - "inference"
    dockerfile: Dockerfile.inference
    platforms:
      - linux/amd64
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"

release:
  github:
    owner: publikey
    name: runqy-worker
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
